Step3 - 자동차 경주 미션
mission-study-to-finish-in-15-days/kotlin-racingcar pull request #27
Opened 2023-08-15 01:58 UTC by Junuu

- InputView는 입력을 요청하기 위한 유저 가이드 메시지에 대한 정보를 담고 있는 클래스입니다.
- InputUtil은 실제 유저의 요청을 받아 CarNumber(자동차의 개수), MoveNumber(움직일 횟수)를 반환합니다.
- RacingCars라는 일급컬렉션을 만들어 자동차 경주게임에 사용될 자동차들을 생성하고 경주를 수행시킵니다.
- Car클래스는 Position(현재위치)와 MoveStrategy interface(움직일 전략)을 가집니다.
- MoveStrategy의 구현체로 RandomMoveStrategy를 구현하며 RandomMoveStrategy는 RandomUtil 인터페이스를 주입받습니다 (추후 테스트를 유연하게 구현하기 위해서)
- ResultView에서는 자동차 List를 받아 현재위치를 라운드마다 출력하도록 합니다.

2023-08-16 03:46 UTC, kji1111 requested changes
이번에는 SAM 써보셨나 보네요 SAM 사용하면 일반 interface보다 장점이 있을까요? 느끼신점 공유 주시면 좋을거 같습니다 ㅎ_ㅎ

2023-08-16 03:57 UTC, kji1111 commented on src/main/kotlin/racingcar/InputUtil.kt
> +object InputUtil {
Util 과 Process 같은 네이밍은 좋아 하지 않는데 혹시 사용할 이유가 있으실까요?

코드 작성 시에 도움이 되는 Singleton 방식의 함수를 사용할때는 util이라는 이름이 좋은거 같은데, 
정책이 정해져 있는 비즈니스 로직 같은 경우는 inputPrompht 와 벨리데이션으로 나누어서 입력 받으면 좋지 않을까 싶습니다 ㅎㅎ
추가로 이번 과제에서는 readln이 keybord 입력이지만 예를 들어서 file 입력을 받을수도 있거든요 그 부분은 InputStream쪽을 참조해 보시면 추상화 할때 도움이 되실거 같습니다.


System.in 객체로 키보드 입력을 받는데 예를 들어서 inputstream으로 file 입력을 받을 수도 있거든요.
```
Scanner(System.`in`)
Scanner(FileInputStream(File("경로")))
```

2023-08-16 09:56 UTC, junuuuuuu commented
> 
사실 SAM(Single Abstract Method)를 의도하고 쓴건아닌데, 아무래도 람다식을 바로 구현체로 활용할 수 있는 장점이 있는것 같습니다 ㅎ

2023-08-16 10:45 UTC, kji6252 commented on src/main/kotlin/racingcar/InputUtil.kt
> +object InputUtil {
https://github.com/kji6252/kotlin-racingcar/blob/47b3e398a096e996650a2a82b63774776aa5ddbb/src/main/kotlin/step3/NoClassRacingCar.kt#L11-L11

여기서 
`val scanner = Scanner(System.`in`)`
를 주석 번갈아서 풀어서 보시면 이해 하시는데 도움이 되실거 같습니다 ㅎ_ㅎ

2023-08-16 11:33 UTC, junuuuuuu commented on src/main/kotlin/racingcar/InputUtil.kt
> +object InputUtil {
종인님의 말씀을 듣고 다시 생각해보니, 입력을 받으며 내부에 비즈니스 로직을 담고있기 때문에 다른곳에서 Input을 활용하지 못할것 같다는 생각이 들어서 Util성 클래스가 아닌것 같네요.

RacingGameInputSupporter로 네이밍을 바꿔야겠습니다 감사합니다ㅎ

2023-08-16 11:38 UTC, junuuuuuu commented on src/main/kotlin/racingcar/InputUtil.kt
> +object InputUtil {
![image](https://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/assets/114379710/918a2710-37e0-498a-b010-a54afc7f1351)
InputStream을 다양하게 구현하는 모습이네요

2023-08-17 12:37 UTC, Hyeon9mak reviewed
안녕하세요 준우님! 3단계도 벌써 Approve 되셨군요... 👍 
숫자야구게임은 아니지만 다음단계 진행하시면서 고민해보실만한 거리를 드리기 위해 코멘트 남깁니다. 😄 
저도 종인님께서 남겨주신 코멘트와 비슷하게, 입력값에 대한 코멘트를 남겼습니다.

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/MoveStrategy.kt
> +    fun move(currentPosition: Position): Position
함수형 인터페이스 선언 👍

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RandomUtil.kt
> +    }
쉽고 편리한 kotlin.random.Random 도 있어요! ThreadLocalRandom 을 사용한 이유가 궁금해요!

```koltin
(0..9).random()
```

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/MoveStrategy.kt
> +        return currentPosition
- 연산자 오버로딩을 이용했으므로 `+` 로 표현도 가능!
- `Position` 에게 1씩 증가한다는 행위를 만들어줄 수도 있겠네요!
- 혹은 현재 구조에서 `Position(1)` 이 계속 생성될 것이므로, `Position(1)` 을 상수로 캐싱해두는 것도 좋겠어요.

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +            ResultView.showCurrentRound(it+1)
"반복 할 때마다 5랩씩 더해서 표기해주세요!" 라는 요구사항이 동료 개발자에게 전달되면 
`ResultView.kt` 와 `RacingCarApplication.kt` 중 어떤 클래스를 먼저 열어볼까요?
현재 repeat 값의 +1 로 표기한다는 건 `ResultView.kt`의 책임 아닐까요? 🤔

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCars.kt
> +) {
`carNumber` 는 최초 생성자에서만 필요 하고 프로퍼티로는 필요 없는 값 같아요.
현재 프로퍼티로 활용될 것처럼 보이는데, 개선할 방법이 있을까요?

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCars.kt
> +    }
repeat 처럼 활용할 수 있는 List 도 있습니다 ㅎ.ㅎ

```kotlin
List(n) { ... }
```

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingGameInputSupporter.kt
> +}
`CarNumber` 와 `MoveNumber` 는 오로지 입력 검증을 담당하는 값인가요, 도메인 전반에 걸쳐서 활용되는 값인가요?
만약 후자라면 현재 패키지 트리 탐색시에 `CarNumber` 와 `MoveNumber` 를 찾기 어려운 상태 같아요. 😱 
`CarNumber` 와 `MoveNumber` 는 자신이 사용자에게 입력 받은 문자열 값이라는 걸 알 필요가 있을까요? 🤔

2023-08-17 12:37 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/ResultView.kt
> +    }
👍 👍 
"문자 `-` 대신 `=`로 출력해주세요." 라는 요구사항이 전달되면 `ResultView` 부터 확인하겠죠 👍 👍

2023-08-17 12:46 UTC, junuuuuuu commented on src/main/kotlin/racingcar/RandomUtil.kt
> +    }
현재는 상관없지만 추후에 멀티스레드 환경에서 더 나은 성능을 제공하기 위해 사용하였습니다.
생성된 난수 등을 추측할 수 없도록 보안적으로 더 강력한 처리가 필요한 경우 SecureRandom을 고려해볼 수 있습니다. (다만 속도가 조금 느리다고 알고 있습니다)

2023-08-17 12:49 UTC, junuuuuuu commented on src/main/kotlin/racingcar/MoveStrategy.kt
> +        return currentPosition
Position(1)을 상수로 캐싱해둔다..! 
좋은생각인것같습니다ㅎ 반영해보겠습니다

2023-08-17 12:54 UTC, junuuuuuu commented on src/main/kotlin/racingcar/RacingCars.kt
> +    }
오 한번 적용해볼게요 ㅎㅎ
(다른 개발자들이 잘 모를것같지만..)

2023-08-17 12:58 UTC, junuuuuuu commented on src/main/kotlin/racingcar/RacingCars.kt
> +) {
의도적으로 다른곳에서는 접근해서 사용할 수 없도록 private으로 막아버렸는데
생성자에 넣지않고 객체를 생성하는 마땅한 방법이 안떠오르네요..

제가 잘 이해를 못한것 같기도 합니다ㅋㅋ

2023-08-17 13:04 UTC, junuuuuuu commented on src/main/kotlin/racingcar/RacingGameInputSupporter.kt
> +}
좋은 내용인것 같습니다.
우선 구현하면서 패키지를 잘 고려하지 않았는데 동료개발자를 위해 domain,vo등으로 패키지를 나누어서 리팩토링을 수행해보겠습니다.
CarNumber와 MoveNumber는 VO로 사용되기 때문에 입력을 받는다는 사실을 알 필요가 없는것 같습니다! 수정하겠습니다.

2023-08-18 05:38 UTC, pado0 commented on src/test/kotlin/racingcar/RacingCarsTest.kt
> +    }
오 이런식으로 전략 변경 유즈케이스 짠거 너무 좋네요 !

2023-08-18 10:15 UTC, junuuuuuu commented on src/test/kotlin/racingcar/RacingCarsTest.kt
> +    }
테스트를 위한 구조를 마련하다보니 인터페이스를 활용하게 되었던것 같습니다ㅋㅋ

2023-08-18 12:35 UTC, merged

2023-08-18 15:25 UTC, Hyeon9mak commented on src/main/kotlin/racingcar/RacingCars.kt
> +) {
`constructor` 키워드를 이용해서 생성자를 별개로 만들거나, 정적 팩터리 메서드를 따로 만들어도 좋을 것 같아요. 👍