feat: 자동차 경주 기능을 완성한다.
mission-study-to-finish-in-15-days/kotlin-racingcar pull request #33
Opened 2023-08-17 16:16 UTC by pado0

자동차 도메인이 이동 정책을 정하는 도메인을 사용해서
회차별로 본인의 위치를 정의합니다..!

이거 랜덤이 있는 코드라 테스트를 고민하기가 어렵네요ㅠ

2023-08-18 00:18 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/ForwardMovingPolicy.kt
> +}
앞 /정지 움직임을 하는 정책을 책임지는 클래스입니다.
RandomDecisionUtil에서 임계치보다 값이 클 경우 앞으로, 작을 경우 stop 합니다.

2023-08-18 00:20 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +    }
경주 차는 ForwardMovingPolicy를 통해 
이동 회차 별로 어느 방향 / 어느 칸 술 이동할지 결정하고 이동까지 진행합니다.

2023-08-18 00:36 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingGame.kt
> +    }
setting(): 입력을 받아 자동차 게임의 기본 조건을 입력받음
ready(): 기본 조건으로 게임 참가 자동차들과 조건을 준비시킴
start(): 자동차 경주 게임을 시작합니다. 자동차들이 이동을 진행합니다.
finish(): 게임 종료!

2023-08-18 00:37 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/io/GameOutput.kt
> +        }
게임 start() 상태에서 회차별로 이동된 자동차의 위치를 출력합니다.

2023-08-18 17:43 UTC, khcho902 requested changes
효진님 3단계 미션 구현하시느라 수고하셨습니다. 
몇가지 코멘트 남겨봤어요!!

2023-08-18 17:43 UTC, khcho902 commented on src/test/kotlin/step3_simple_racing_car/RandomDecisionUtilTest.kt
> +class RandomDecisionUtilTest : StringSpec({
랜덤에 대한 부분도 따로 테스트해주셨군요 👍

2023-08-18 17:43 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingGame.kt
> +    fun setting() = GameOptionInput.input()
RacingGame은 이번 미션에서 가장 핵심이 되는 도메인 코드로 보입니다. 
도메인코드에서 입출력관련 코드에 의존하고 있는거 같아요! 

Main클래스인 RacingGameApplication에서  입출력관련된 부분을 처리하고, 
RacingGame 클래스에 필요한 값들만 넘겨주는 형태는 어떨까요?

2023-08-18 17:43 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/io/GameOutput.kt
> +            println()
```suggestion
            println("-".repeat(it.position.value))
```
제꺼 미션에서 쓴 코드 공유합니다. ㅎㅎ

2023-08-18 17:43 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingGame.kt
> +    var movingCount: Int = 0
participants의 경우 외부에서 바로 접근해서 새로운 racingCar를 추가할수도 있을거 같아요! 
private으로 감추고,  외부에 노출 시킬 필요가 있으면 immutable list로 반환하도록 해도 좋을거같아요!! 

movingCount는 외부에서 사용하고 있지 않는거 같아서 private으로 해줘도  좋을거 같아요!

2023-08-18 17:43 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +    private var movingPolicy: ForwardMovingPolicy = ForwardMovingPolicy(direction = MovingDirectionType.STOP)
RacingCar가 움직이는 정책을 주입받도록 하셨군요!👍

MovingPolicy 인터페이스를 만들고,  
상황에 맞게 랜덤으로 전진하는 정책, 항상 전진하는 정책을 만들어서 RacingCar에 주입해주면 테스트하기에도 좀 더 용이할거 같아요!!

2023-08-20 05:33 UTC, Hyeon9mak reviewed
안녕하세요 효진님, 경현님이 좋은 리뷰 남겨주셨네요 👍 
간단한 코멘트 남기고 지나갑니다~

> 이거 랜덤이 있는 코드라 테스트를 고민하기가 어렵네요ㅠ

- 꼭 랜덤에 대해서 테스트가 필요할까요?
- 테스트가 어렵다는 건 내부 의존 객체가 많다는 것 같아요.
- 저희가 객체지향, 스프링을 지겹도록 공부하면서 익힌 의존성 분리 방법이 있죠~ `생성자 주입`, `메서드 파라미터 주입`

2023-08-20 05:33 UTC, Hyeon9mak commented on src/main/kotlin/step3_simple_racing_car/domain/RacingGame.kt
> +    }
repeat 대신 List 라는 키워드도 있습니다. 😎 

```kotlin
val cars = List(n) { ... }
```

2023-08-20 05:33 UTC, Hyeon9mak commented on src/main/kotlin/step3_simple_racing_car/io/GameOptionInput.kt
> +    }
현재 DTO 와 Input 전담 객체가 하나로 통합된 형태로 보여요.
이 둘을 합쳤을 때와 분리했을 때 각각 장단점은 무엇일까요?

2023-08-20 05:33 UTC, Hyeon9mak commented on src/main/kotlin/step3_simple_racing_car/io/GameOptionInput.kt
> +    }
코틀린 컨벤션으로 동반객체(companion object)는 가장 아래에 두는 것 같아요!

2023-08-20 05:33 UTC, Hyeon9mak commented on src/main/kotlin/step3_simple_racing_car/vo/Position.kt
> +}
프로퍼티가 1개 이므로 value class 를 활용할 수도 있겠네요~

2023-08-20 11:43 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/vo/Position.kt
> +}
오 두분 의견 감사합니다! 현구님 추천대로 value 클래스 이용해보겠습니다!

2023-08-20 11:58 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingGame.kt
> +    fun setting() = GameOptionInput.input()
오 제가 RacingGame을 도메인으로 만들어놓고
그 안에서 io를 다 참조하고있었네요..! 
Racing Game이라는 명시적인 게임 도메인을 만들고싶었는데,
게임 도메인에서 입력 / 출력을 받으니 IO를 사용한다는 생각의 흐름때문에 이렇게 되었나봐요.

말씀주신대로 Application 단에서 처리하면 되는 로직을 끌고 들어온 것 같아
의존성 없도록 빼버리겠습니다. 좋은 리뷰 감사합니다!

2023-08-20 12:21 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingGame.kt
> +    var movingCount: Int = 0
오오 좋은 의견 감사합니다.
배킹프로퍼티로 var이거나 mutable인 필드는 val, immutable로 변환해서 조회하도록 하겠습니다!

2023-08-20 12:30 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +    private var movingPolicy: ForwardMovingPolicy = ForwardMovingPolicy(direction = MovingDirectionType.STOP)
이동 정책을 결정하는 MovingPolicy 인터페이스를 만들고,
policy 생성 / policy의 방향과 이동 칸 수를 지정할 수 있게 하는 방향으로 작업해보겠습니다!  
(이동 정책이 달라도 방향 , 칸 수는 공통 정의되어야한다고 가정)

2023-08-20 12:39 UTC, pado0 commented
> 안녕하세요 효진님, 경현님이 좋은 리뷰 남겨주셨네요 👍 간단한 코멘트 남기고 지나갑니다~
> 
> > 이거 랜덤이 있는 코드라 테스트를 고민하기가 어렵네요ㅠ
> 
> * 꼭 랜덤에 대해서 테스트가 필요할까요?
> * 테스트가 어렵다는 건 내부 의존 객체가 많다는 것 같아요.
> * 저희가 객체지향, 스프링을 지겹도록 공부하면서 익힌 의존성 분리 방법이 있죠~ `생성자 주입`, `메서드 파라미터 주입`

오호 랜덤에 대해 테스트를 꼭 해야하는가..? 에 대해서는 
금번 미션의 핵심 로직이라고 생각해서 테스트에 포함되어야 한다고 생각했습니다.
다만 테스트를 작성하더라도 회귀방지, 리팩토링 내성등이... 100% 보장되진 않을 것이니 작성이 무의미할 수도 있겠네요.!

2023-08-20 12:40 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/io/GameOutput.kt
> +            println()
오이거 알고리즘때 쓰던 습관이..ㅋㅋㅋ 다른건 다 고쳤는데 이부분만 repeat()으로 바꾸는걸 누락했군요..!!
경현님 추천코드 복붙 갑니다 ㅎㅎ 감사합니다!

2023-08-20 13:06 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/io/GameOptionInput.kt
> +    }
[합쳤을 때]
장: 
Input을 받고 validation을 적용해서 넘기는 부분까지 하나의 객체에서 처리할 수 있다.
입력에 대한 모든 처리를 집약시킬 수 있다. 입력을 전담하는 객체라는 관점에서 합쳐서 작업해놨던 것 같다!

단: 
생명주기가 다른 두 기능을 합쳐놓아 분리가 필요해보인다.
위처럼 클래스를 구성했을 때 Input 객체가 DTO처럼 보이게 되는데, 
DTO에 무언가의 비즈니스 로직을 넣는게 DTO의 역할에 맞지 않다.
사실 이동 횟수와 참가자 수는 Input에서 유효성 검증을 할 것이 아니고, RacingGame에서 해주는게 맞아보인다.

좋은 코멘트 감사합니다 현구님!
분리해놔야겠네요 ㅎㅎ (절하는 이모지)

2023-08-20 13:40 UTC, khcho902 approved these changes
효진님 리뷰남긴것들에 대해서 잘 반영해주셔서 approve 하겠습니다. 
수고하셨어요!! 😁

추가적으로 몇가지 코멘트 남겨봤는데,  다음단계 진행할때 참고해주세요!! 🙇🏻‍♂️

2023-08-20 13:40 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/util/RandomDecisionUtil.kt
> +    ): Boolean = (0..9).random() >= threshold!!
threshold: Int로 사용하면 !!를 굳이 사용하지 않아도 되겠네요!

2023-08-20 13:40 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/domain/MovingPolicy.kt
> +    fun getMovingCount(): Int
MovingPolicy는 방향과 움직일 거리를 둘다 제공하는군요! 👍

2023-08-20 13:40 UTC, khcho902 commented on src/test/kotlin/step3_simple_racing_car/RacingCarMovingTest.kt
> +class RacingCarMovingTest : StringSpec({
RacingCar에서 가장 핵심이 되는 테스트는 정책에 맞게 잘동작하는가?? 인거 같아요!! 

MovingPolicy를 인터페이스로 만들어주셨으므로,  
아래와 같이 테스트하기 쉬운 MovingPolicy를 구현하고, RacingCar가 정책에 맞게 잘 동작하는지 테스트할수 있을거 같아요!! 

```
val alwaysForwardMovingPolicy = object: MovingPolicy{
    override fun makePolicy(): MovingPolicy {
        return this
    }

    override fun getMovingDirection(): MovingDirectionType {
        return MovingDirectionType.FORWARD
    }

    override fun getMovingCount(): Int {
        return 1
    }
}
```

2023-08-20 13:47 UTC, khcho902 commented on src/test/kotlin/step3_simple_racing_car/RacingCarMovingTest.kt
> +class RacingCarMovingTest : StringSpec({
RacingCar가 랜덤하게 동작하기때문에  타이트한 테스트코드를 작성하지 못하신거같은데,
MovingPolicy라는 interface가 있기때문에, 상황에 맞게  MovingPolicy를 구현해서 RacingCar에 넘겨주면 좋을거 같아요!!

2023-08-20 14:14 UTC, pado0 commented on src/test/kotlin/step3_simple_racing_car/RacingCarMovingTest.kt
> +class RacingCarMovingTest : StringSpec({
좋은 의견 감사합니다!
말씀주신대로 테스트하기 쉬운 Policy를 작성하는 것도 방법이겠네요!!

2023-08-20 14:19 UTC, pado0 commented on src/test/kotlin/step3_simple_racing_car/RacingCarMovingTest.kt
> +class RacingCarMovingTest : StringSpec({
4단계할떄................테스트코드를.........고쳐보도록하겠습니다!!!!!!!!!!

2023-08-20 14:19 UTC, merged