feat: step4 - 우승자가 있는 자동차 경주
mission-study-to-finish-in-15-days/kotlin-racingcar pull request #39
Opened 2023-08-20 15:29 UTC by pado0

2023-08-21 01:14 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +        position = position.move(policy.getMovingCount())
외부에서 이동 정첵을 받아서 이동하는 것으로 수정했습니다.
다만, MovingDirection의 역할이... 정책과 무관하게 그냥 회차별 이동 방향으로 쓰이고 있어서
수정이 필요해보입니다. (찔려서 얘기해봅니다)

2023-08-21 11:32 UTC, khcho902 requested changes
효진님 3단계에서 잘해주셔서 딱히 남길 리뷰가 많이 없네요 ㅎㅎ 
요구사항 누락이 있어 일단 Request chagnes!! ㅋㅋ

2023-08-21 11:32 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +        position = position.move(policy.getMovingCount())
12, 13번라인 코드를 보면서  갑자기 이런생각이 들었어요!! 

getMovingCount 반환값이 Int이므로  양수면 앞으로이동, 음수면 뒤로이동, 0이면 정지!! 
굳이 RacingCar가 MovingDirection은 몰라도 되지 않을까?라는 생각을 해봤습니다. ㅎㅎ 
```
  override fun getMovingCount(): Int {
      val direction = when(direction) {
          MovingDirectionType.FORWARD -> 1
          MovingDirectionType.STOP -> 0
      }
      return direction * movingCount
  }
```



다른부분 마땅히 코멘드 남길게 없어서 남겨보았습니다!! 😁

2023-08-21 11:32 UTC, khcho902 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +    val nickName: String,
앗  아래의 요구사항이 누락된거 같아요!! 
>  자동차 이름은 5자를 초과할 수 없다.

2023-08-22 03:35 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +    val nickName: String,
아헐 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ이거 준우님 코드보고 자체 usecase 추가하신건가 했는데
제가 제대로 보지 않은거군요 추가해두겠습니다!!

2023-08-22 03:36 UTC, pado0 commented on src/main/kotlin/step3_simple_racing_car/domain/RacingCar.kt
> +        position = position.move(policy.getMovingCount())
오 넵 맞아요! 사실 RacingCar가 방향을 몰라도 되는게 맞는 것 같습니다! 코멘트 반영해볼게욥!

2023-08-22 09:46 UTC, Hyeon9mak reviewed
안녕하세요 효진님, 간단한 코멘트 남겼습니다.

2023-08-22 09:46 UTC, Hyeon9mak commented on src/main/kotlin/step3_simple_racing_car/domain/RacingGame.kt
>  ) {
(여유가 있다면) `3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.`, `일급 컬렉션을 쓴다.` 를 지키기 위해 적절하게 분리해보는 것도 좋겠어요.

2023-08-23 10:53 UTC, khcho902 approved these changes
내일이 마지막이므로 언능 5단계 하시라고 approve 드립니다!! 
딱히 고칠것도 별로 없었음 ㅎㅎ

2023-08-23 14:33 UTC, pado0 commented
두분 코멘트 감사합니다!
마침..마지막 과제가 리팩토링이므로 step5에서 수정 반영 차근차근 해보도록 하겠습니다!

2023-08-23 14:33 UTC, merged